name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  firebase_core: ^2.9.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.0.11
  image_picker: ^1.0.4
  country_code_picker: ^3.0.0
  dotted_border: ^2.0.0+2
  percent_indicator: ^4.0.1
  url_launcher: ^6.1.3
  flutter_html: ^3.0.0-alpha.5
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.9
  shimmer_animation: ^2.1.0+1
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  syncfusion_flutter_datepicker: ^23.1.44
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_animarker: ^3.2.0
  expandable_bottom_sheet: ^1.1.1+1
  carousel_slider: ^4.1.1
  shimmer: ^3.0.0
  loading_overlay_pro: ^2.1.1
  modal_bottom_sheet: ^2.1.2
  flutter_widget_from_html_core: ^0.14.7
  flutter_typeahead: ^4.3.7
  dotted_line: ^3.1.0
  autocomplete_textfield: ^2.0.1
  web_socket_channel: ^2.3.0
  flutter_inappwebview: ^5.7.2+3
  firebase_crashlytics: ^3.2.0
  screenshot: ^2.1.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900
